Implement linting with ktlint
bitwiseio/sawtooth-sdk-java pull request #10
Opened 2018-12-12 17:35 UTC by shannynalayna

Lints the sawtooth xo app using ktlint from the command line. Also renames the project from ```sawtooth_xo``` to ```sawtoothXO``` and the internal directory ```rest_api``` to ```restApi``` to comply with package and directory naming conventions which disallow underscores. 

This current linting is done through the the command line and dependent on PR #9. 

In order to perform linting, download ktlint (can use ```brew install ktlint```) and then simply run the command ```ktlint``` from the project's source directory or you may specify files as optional arguments with this command. With this PR, there should be no feedback after this command. If there are any issues, the command will return the file location and the linting warning.

2018-12-12 17:40 UTC, boydjohnson commented
Is it possible to have ktlint part of the gradle script?

2018-12-12 17:46 UTC, shannynalayna commented
@boydjohnson I've tried to get it integrated but have been running into a few issues while actually running it with the gradle script, so still working on that!

2018-12-13 21:32 UTC, boydjohnson requested changes
Commented out code.

2018-12-13 21:32 UTC, boydjohnson commented on examples/xo_android_client/app/build.gradle
> +    // to generate report in checkstyle format prepend following args:
We shouldn't have commented out code.

2018-12-13 21:52 UTC, boydjohnson approved these changes

2018-12-17 16:27 UTC, dplumb94 approved these changes
I had to do `brew install shyiko/ktlint/ktlint` to install. Tested, works!

2018-12-17 17:10 UTC, merged